# Manifesto de Servi√ßos - Redstone OS
# /system/manifests/services.toml

[init]
path = "/system/core/init"
restart = "never"
depends = []

# [console]
# path = "/system/services/console"
# restart = "always"
# depends = []

# [devices]
# path = "/system/services/devices"
# restart = "always"
# depends = ["console"]

# [vfs]
# path = "/system/services/vfs"
# restart = "on-failure"
# depends = ["devices"]

# [logger]
# path = "/system/services/logger"
# restart = "always"
# depends = []