# Manifesto de Servi√ßos - Redstone OS
# /system/manifests/services.toml

[init]
path = "/system/core/init"
restart = "never"
depends = []

# [console]
# path = "/system/services/console"
# restart = "always"
# depends = []
